# Controller Parameters

artpark_robot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

  # Effort Controllers ---------------------------------------
  trash_holder_joint_effort_controller:
    type: effort_controllers/JointEffortController
    joint: trash_holder_joint
    # pid: {p: 100.0, i: 0.01, d: 1.0}

  mop_joint_effort_controller:
    type: effort_controllers/JointEffortController
    joint: mop_joint
    # pid: {p: 100.0, i: 0.01, d: 1.0}
  
  arm_body_joint_effort_controller:
    type: effort_controllers/JointEffortController
    joint: arm_body_joint
    # pid: {p: 100.0, i: 0.01, d: 1.0}

  arm_base_joint_effort_controller:
    type: effort_controllers/JointEffortController
    joint: arm_base_joint
    # pid: {p: 100.0, i: 0.01, d: 1.0}

  # arm_stretch1_joint_effort_controller:
  #   type: effort_controllers/JointEffortController
  #   joint: arm_stretch1_joint
  #   # pid: {p: 100.0, i: 0.01, d: 1.0}

  # arm_stretch2_joint_effort_controller:
  #   type: effort_controllers/JointEffortController
  #   joint: arm_stretch2_joint
  #   # pid: {p: 10.0, i: 0.01, d: 10.0}
  
  # hand_joint_effort_controller:
  #   type: effort_controllers/JointEffortController
  #   joint: hand_joint
  #   # pid: {p: 100.0, i: 0.01, d: 1.0}

  # finger_left_joint_effort_controller:
  #   type: effort_controllers/JointEffortController
  #   joint: finger_left_joint
  #   # pid: {p: 100.0, i: 0.01, d: 1.0}

  # finger_right_joint_effort_controller:
  #   type: effort_controllers/JointEffortController
  #   joint: finger_right_joint
  #   # pid: {p: 100.0, i: 0.01, d: 1.0}

  # body_joint_effort_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: body_joint
  #   pid: {p: 5.0, i: 0.1, d: 0.15}

  # front_left_caster_joint_effort_controller:
  #   type: effort_controllers/JointEffortController
  #   joint: front_left_caster_joint
  #   pid: {p: 15.0, i: 0.1, d: 0.15}
  
  # front_right_caster_joint_effort_controller:
  #   type: effort_controllers/JointEffortController
  #   joint: front_right_caster_joint
  #   pid: {p: 15.0, i: 0.1, d: 0.15}
  
  # rear_left_caster_joint_effort_controller:
  #   type: effort_controllers/JointEffortController
  #   joint: rear_left_caster_joint
  #   pid: {p: 15.0, i: 0.1, d: 0.15}
  
  # rear_right_caster_joint_effort_controller:
  #   type: effort_controllers/JointEffortController
  #   joint: rear_right_caster_joint
  #   pid: {p: 15.0, i: 0.1, d: 0.15}

  # body_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: body_joint
  #   pid: {p: 5.0, i: 0.0, d: 0.15}

  front_left_wheel_joint_effort_controller:
    type: effort_controllers/JointEffortController
    joint: front_right_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  
  front_right_wheel_joint_effort_controller:
    type: effort_controllers/JointEffortController
    joint: front_right_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  
  rear_left_wheel_joint_effort_controller:
    type: effort_controllers/JointEffortController
    joint: rear_left_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  rear_right_wheel_joint_effort_controller:
    type: effort_controllers/JointEffortController
    joint: rear_right_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  
  camera_top_joint_effort_controller:
    type: effort_controllers/JointEffortController
    joint: camera_top_joint
    # pid: {p: 10.0, i: 0.01, d: 10.0}

  camera_bottom_joint_effort_controller:
    type: effort_controllers/JointEffortController
    joint: camera_bottom_joint
    # pid: {p: 100.0, i: 0.01, d: 10.0}
  
  camera_top_balance_joint_effort_controller:
    type: effort_controllers/JointEffortController
    joint: camera_top_balance_joint
    # pid: {p: 100.0, i: 0.01, d: 10.0}

  # laser_joint_effort_controller:
  # type: effort_controllers/JointEffortController
  # joint: laser_joint
  # pid: {p: 100.0, i: 0.01, d: 10.0}


  panda_joint3_joint_effort_controller:
    type: effort_controller_JointEffotController
    joint: trans_panda_joint3
    pid: {p: 1.0, i: 1.0, d: 0.0}
  
  panda_joint4_joint_effort_controller:
    type: effort_controller_JointEffotController
    joint: trans_panda_joint3
    pid: {p: 1.0, i: 1.0, d: 0.0}

  panda_joint5_joint_effort_controller:
    type: effort_controller_JointEffotController
    joint: trans_panda_joint3
    pid: {p: 1.0, i: 1.0, d: 0.0}

  panda_joint6_joint_effort_controller:
    type: effort_controller_JointEffotController
    joint: trans_panda_joint3
    pid: {p: 1.0, i: 1.0, d: 0.0}

  panda_joint7_joint_effort_controller:
    type: effort_controller_JointEffotController
    joint: trans_panda_joint3
    pid: {p: 1.0, i: 1.0, d: 0.0}
  
  panda_finger_joint1_joint_effort_controller:
    type: effort_controller_JointEffotController
    joint: trans_panda_joint3
    pid: {p: 1.0, i: 1.0, d: 0.0}

  panda_finger_joint2_joint_effort_controller:
    type: effort_controller_JointEffotController
    joint: trans_panda_joint3
    pid: {p: 1.0, i: 1.0, d: 0.0}